from __future__ import annotations

from typing import Any


PARAMETERS: dict[str, list[dict[str, Any]]] = {
    "pinwheel": [
        {"key": "chunk_size", "label": "Notes per Pinwheel", "type": "int", "min": 4, "max": 4096, "default": 256},
        {"key": "center_x", "label": "Center X", "type": "float", "min": 0, "max": 512, "default": 256, "step": 1},
        {"key": "center_y", "label": "Center Y", "type": "float", "min": 0, "max": 384, "default": 192, "step": 1},
        {"key": "num_blades", "label": "Blades", "type": "int", "min": 1, "max": 24, "default": 6},
        {"key": "blade_curl", "label": "Blade Curl", "type": "float", "min": -4, "max": 4, "default": 0.8, "step": 0.05},
        {"key": "rotation_offset_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
        {"key": "blade_spread_deg", "label": "Blade Spread", "type": "float", "min": 0, "max": 360, "default": 60, "step": 1},
        {"key": "inner_radius", "label": "Inner Radius", "type": "float", "min": 0, "max": 190, "default": 18, "step": 1},
        {"key": "outer_radius", "label": "Outer Radius", "type": "float", "min": 1, "max": 256, "default": 170, "step": 1},
        {"key": "wander_strength", "label": "Wander Strength", "type": "float", "min": 0, "max": 80, "default": 8, "step": 1},
        {"key": "wander_seed", "label": "Wander Seed", "type": "int", "min": 0, "max": 999999, "default": 12345},
        {"key": "inner_circle_notes", "label": "Inner Circle Notes", "type": "int", "min": 1, "max": 512, "default": 24},
        {"key": "inner_circle_radius", "label": "Inner Circle Radius", "type": "float", "min": 1, "max": 190, "default": 18, "step": 1},
        {"key": "inner_circle_enabled", "label": "Inner Circle", "type": "choice", "choices": [("Enabled", True), ("Disabled", False)], "default": True},
        {"key": "radius_growth_curve", "label": "Radius Growth", "type": "choice", "choices": [("Linear", "linear"), ("Ease Out", "ease_out"), ("Ease In", "ease_in")], "default": "ease_out"},
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
    ],
    "equation": [
        {"key": "graph_size", "label": "Graph Size (%)", "type": "int", "min": 10, "max": 300, "default": 100},
        {"key": "equation_mode", "label": "Graph Type", "type": "choice", "choices": [("Explicit", "explicit"), ("Implicit", "implicit"), ("Parametric", "parametric")], "default": "implicit"},
        {"key": "equation", "label": "Equation", "type": "text", "default": "tan(x^2+y^2)=1{|x|<3}{|y|<3}"},
        {"key": "x_expression", "label": "x(t)", "type": "text", "default": "cos(3*t)"},
        {"key": "y_expression", "label": "y(t)", "type": "text", "default": "sin(2*t)"},
        {"key": "x_min", "label": "X Minimum", "type": "float", "min": -100, "max": 100, "default": -5, "step": 0.1},
        {"key": "x_max", "label": "X Maximum", "type": "float", "min": -100, "max": 100, "default": 5, "step": 0.1},
        {"key": "y_min", "label": "Y Minimum", "type": "float", "min": -100, "max": 100, "default": -3.75, "step": 0.1},
        {"key": "y_max", "label": "Y Maximum", "type": "float", "min": -100, "max": 100, "default": 3.75, "step": 0.1},
        {"key": "t_min", "label": "t Minimum", "type": "float", "min": -100, "max": 100, "default": 0, "step": 0.1},
        {"key": "t_max", "label": "t Maximum", "type": "float", "min": -100, "max": 100, "default": 6.283, "step": 0.1},
        {"key": "resolution", "label": "Resolution", "type": "int", "min": 32, "max": 384, "default": 160},
        {"key": "chunk_size", "label": "Notes per Curve", "type": "int", "min": 2, "max": 4096, "default": 256},
        {"key": "margin_x", "label": "Margin X", "type": "int", "min": 0, "max": 255, "default": 20},
        {"key": "margin_y", "label": "Margin Y", "type": "int", "min": 0, "max": 191, "default": 20},
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
    ],
    "text": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "text_size", "label": "Text Size (%)", "type": "int", "min": 20, "max": 100, "default": 90},
        {"key": "chunk_size", "label": "Notes per Text", "type": "int", "min": 2, "max": 2048, "default": 128},
        {"key": "text", "label": "Text", "type": "text", "default": "67"},
        {"key": "margin_x", "label": "Margin X", "type": "int", "min": 0, "max": 255, "default": 20},
        {"key": "margin_y", "label": "Margin Y", "type": "int", "min": 0, "max": 191, "default": 20},
        {"key": "reverse", "label": "Direction", "type": "choice", "choices": [("Forward", False), ("Reverse", True)], "default": False},
    ],
    "horizontal": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "line_count", "label": "Lines", "type": "int", "min": 1, "max": 32, "default": 8},
        {"key": "notes_per_line", "label": "Notes per line", "type": "int", "min": 1, "max": 128, "default": 16},
        {"key": "margin_x", "label": "Margin X", "type": "int", "min": 0, "max": 255, "default": 12},
        {"key": "margin_y", "label": "Margin Y", "type": "int", "min": 0, "max": 191, "default": 10},
        {"key": "direction", "label": "Direction", "type": "choice", "choices": [("Left to Right", "left_to_right"), ("Right to Left", "right_to_left")], "default": "left_to_right"},
    ],
    "vertical": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "line_count", "label": "Columns", "type": "int", "min": 1, "max": 32, "default": 8},
        {"key": "notes_per_line", "label": "Notes per column", "type": "int", "min": 1, "max": 128, "default": 16},
        {"key": "margin_x", "label": "Margin X", "type": "int", "min": 0, "max": 255, "default": 12},
        {"key": "margin_y", "label": "Margin Y", "type": "int", "min": 0, "max": 191, "default": 10},
        {"key": "direction", "label": "Direction", "type": "choice", "choices": [("Top to Bottom", "top_to_bottom"), ("Bottom to Top", "bottom_to_top")], "default": "top_to_bottom"},
    ],
    "circle": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per circle", "type": "int", "min": 2, "max": 256, "default": 36},
        {"key": "radius", "label": "Radius", "type": "float", "min": 10, "max": 190, "default": 150, "step": 1},
        {"key": "center_x", "label": "Center X", "type": "float", "min": 0, "max": 512, "default": 256, "step": 1},
        {"key": "center_y", "label": "Center Y", "type": "float", "min": 0, "max": 384, "default": 192, "step": 1},
        {"key": "rotation_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
    ],
    "ellipse": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per ellipse", "type": "int", "min": 2, "max": 256, "default": 48},
        {"key": "radius_x", "label": "Radius X", "type": "float", "min": 10, "max": 250, "default": 200, "step": 1},
        {"key": "radius_y", "label": "Radius Y", "type": "float", "min": 10, "max": 190, "default": 120, "step": 1},
        {"key": "rotation_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
    ],
    "square": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per square", "type": "int", "min": 4, "max": 256, "default": 32},
        {"key": "side_length", "label": "Side length", "type": "float", "min": 20, "max": 380, "default": 280, "step": 1},
        {"key": "rotation_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
    ],
    "triangle": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per triangle", "type": "int", "min": 3, "max": 256, "default": 30},
        {"key": "radius", "label": "Radius", "type": "float", "min": 10, "max": 190, "default": 160, "step": 1},
        {"key": "rotation_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
    ],
    "diamond": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per diamond", "type": "int", "min": 4, "max": 256, "default": 32},
        {"key": "width", "label": "Width", "type": "float", "min": 20, "max": 500, "default": 320, "step": 1},
        {"key": "height", "label": "Height", "type": "float", "min": 20, "max": 380, "default": 260, "step": 1},
        {"key": "rotation_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
    ],
    "infinity": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per infinity", "type": "int", "min": 4, "max": 256, "default": 64},
        {"key": "width", "label": "Width", "type": "float", "min": 20, "max": 500, "default": 380, "step": 1},
        {"key": "height", "label": "Height", "type": "float", "min": 20, "max": 380, "default": 220, "step": 1},
        {"key": "rotation_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
    ],
    "star": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per star", "type": "int", "min": 5, "max": 256, "default": 32},
        {"key": "points", "label": "Star points", "type": "int", "min": 3, "max": 16, "default": 5},
        {"key": "outer_radius", "label": "Outer radius", "type": "float", "min": 10, "max": 190, "default": 170, "step": 1},
        {"key": "inner_radius", "label": "Inner radius", "type": "float", "min": 5, "max": 180, "default": 75, "step": 1},
        {"key": "rotation_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
    ],
    "spiral": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per spiral", "type": "int", "min": 2, "max": 256, "default": 80},
        {"key": "turns", "label": "Turns", "type": "float", "min": 0.25, "max": 8, "default": 2.5, "step": 0.05},
        {"key": "start_radius", "label": "Start radius", "type": "float", "min": 0, "max": 180, "default": 0, "step": 1},
        {"key": "end_radius", "label": "End radius", "type": "float", "min": 1, "max": 190, "default": 170, "step": 1},
        {"key": "rotation_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
    ],
    "arc": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per arc", "type": "int", "min": 2, "max": 256, "default": 24},
        {"key": "radius_x", "label": "Radius X", "type": "float", "min": 10, "max": 250, "default": 180, "step": 1},
        {"key": "radius_y", "label": "Radius Y", "type": "float", "min": 10, "max": 190, "default": 130, "step": 1},
        {"key": "start_angle_deg", "label": "Start angle", "type": "float", "min": -360, "max": 360, "default": -180, "step": 1},
        {"key": "sweep_angle_deg", "label": "Sweep angle", "type": "float", "min": -360, "max": 360, "default": 180, "step": 1},
    ],
    "straight_line": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per line", "type": "int", "min": 2, "max": 256, "default": 16},
        {"key": "length", "label": "Length", "type": "float", "min": 10, "max": 500, "default": 400, "step": 1},
        {"key": "rotation_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
    ],
    "wave": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per wave", "type": "int", "min": 2, "max": 256, "default": 32},
        {"key": "width", "label": "Width", "type": "float", "min": 20, "max": 500, "default": 440, "step": 1},
        {"key": "amplitude", "label": "Amplitude", "type": "float", "min": 1, "max": 190, "default": 100, "step": 1},
        {"key": "cycles", "label": "Cycles", "type": "float", "min": 0.25, "max": 8, "default": 2, "step": 0.05},
        {"key": "phase_deg", "label": "Phase", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
        {"key": "rotation_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
    ],
    "zigzag": [
        {"key": "back_and_forth", "label": "Traversal", "type": "choice", "choices": [("Restart Each Chunk", False), ("Back and Forth", True)], "default": False},
        {"key": "chunk_size", "label": "Notes per zigzag", "type": "int", "min": 2, "max": 256, "default": 48},
        {"key": "width", "label": "Width", "type": "float", "min": 20, "max": 500, "default": 440, "step": 1},
        {"key": "height", "label": "Height", "type": "float", "min": 20, "max": 380, "default": 240, "step": 1},
        {"key": "segments", "label": "Segments", "type": "int", "min": 1, "max": 32, "default": 8},
        {"key": "rotation_deg", "label": "Rotation", "type": "float", "min": 0, "max": 360, "default": 0, "step": 1},
    ],
    "random_walk": [
        {"key": "seed", "label": "Seed", "type": "int", "min": 0, "max": 999999, "default": 12345},
        {"key": "step_size", "label": "Step size", "type": "float", "min": 1, "max": 100, "default": 35, "step": 1},
        {"key": "max_turn_deg", "label": "Maximum turn", "type": "float", "min": 1, "max": 180, "default": 55, "step": 1},
        {"key": "margin_x", "label": "Margin X", "type": "int", "min": 0, "max": 255, "default": 20},
        {"key": "margin_y", "label": "Margin Y", "type": "int", "min": 0, "max": 191, "default": 20},
    ],
    "random": [
        {"key": "chunk_size", "label": "Notes per chunk", "type": "int", "min": 1, "max": 256, "default": 64},
        {"key": "seed", "label": "Seed", "type": "int", "min": 0, "max": 999999, "default": 12345},
        {"key": "margin_x", "label": "Margin X", "type": "int", "min": 0, "max": 255, "default": 20},
        {"key": "margin_y", "label": "Margin Y", "type": "int", "min": 0, "max": 191, "default": 20},
    ],
    "taiko": [
        {"key": "beats_per_line", "label": "Beats per line", "type": "float", "min": 0.25, "max": 16, "default": 2, "step": 0.25},
        {"key": "line_count", "label": "Lines", "type": "int", "min": 1, "max": 32, "default": 8},
        {"key": "margin_x", "label": "Margin X", "type": "int", "min": 0, "max": 255, "default": 12},
        {"key": "margin_y", "label": "Margin Y", "type": "int", "min": 0, "max": 191, "default": 10},
        {"key": "min_bpm", "label": "Minimum BPM", "type": "float", "min": 1, "max": 500, "default": 30, "step": 1},
        {"key": "max_bpm", "label": "Maximum BPM", "type": "float", "min": 30, "max": 10000, "default": 1000, "step": 10},
    ],
    "vertical_taiko": [
        {"key": "beats_per_line", "label": "Beats per line", "type": "float", "min": 0.25, "max": 16, "default": 2, "step": 0.25},
        {"key": "line_count", "label": "Columns", "type": "int", "min": 1, "max": 32, "default": 8},
        {"key": "margin_x", "label": "Margin X", "type": "int", "min": 0, "max": 255, "default": 12},
        {"key": "margin_y", "label": "Margin Y", "type": "int", "min": 0, "max": 191, "default": 10},
        {"key": "min_bpm", "label": "Minimum BPM", "type": "float", "min": 1, "max": 500, "default": 30, "step": 1},
        {"key": "max_bpm", "label": "Maximum BPM", "type": "float", "min": 30, "max": 10000, "default": 1000, "step": 10},
        {"key": "direction", "label": "Direction", "type": "choice", "choices": [("Top to Bottom", "top_to_bottom"), ("Bottom to Top", "bottom_to_top")], "default": "top_to_bottom"},
    ],
    "dvd_bouncing": [
        {"key": "seed", "label": "Seed", "type": "int", "min": 0, "max": 999999, "default": 12345},
        {"key": "step_size", "label": "Step size", "type": "float", "min": 1, "max": 150, "default": 35, "step": 1},
        {"key": "margin_x", "label": "Margin X", "type": "int", "min": 0, "max": 255, "default": 20},
        {"key": "margin_y", "label": "Margin Y", "type": "int", "min": 0, "max": 191, "default": 20},
    ],
}
