from __future__ import annotations
import re

JA = {
"Open .osu":".osu を開く","Play":"再生","Pause":"一時停止","Reset applied transforms":"適用した変形をリセット","Export applied map":"適用済み譜面をエクスポート","Difficulty":"難易度","Playback Rate":"再生速度","Background Opacity":"背景の不透明度","Transformation mode":"変形モード","All Notes":"すべてのノーツ","Split Don / Kat":"ドン / カッを分割","Swap Don ↔ Kat":"ドン ↔ カッを入れ替え","Transform selected notes":"選択したノーツを変形","Apply all changes to original file":"すべての変更を元のファイルに適用","Beat snap":"ビートスナップ","Duration":"曲の長さ","Now":"現在","Snap":"スナップ","Wheel: seek":"ホイール: シーク","Shift+wheel: 1 beat":"Shift+ホイール: 1拍","Ctrl+wheel: zoom":"Ctrl+ホイール: ズーム","All":"すべて","Don":"ドン","Kat":"カッ","None":"なし","Open Settings":"設定を開く","Open osu! beatmap":"osu! 譜面を開く","osu! beatmaps (*.osu)":"osu! 譜面 (*.osu)",
"Position X":"X位置","Position Y":"Y位置","Traversal":"進行方法","Font":"フォント","Random Seed":"ランダムシード","Direction":"方向","Rotation":"回転","Column":"列","Columns":"列数","Min BPM":"最小BPM","Max BPM":"最大BPM","Minimum BPM":"最小BPM","Maximum BPM":"最大BPM","Step Size":"ステップ幅","Step size":"ステップ幅","Chunk":"チャンク","Chunk Size":"チャンクサイズ","Notes per Chunk":"チャンクあたりのノーツ数","Max Turn":"最大旋回角","Maximum Turn":"最大旋回角","Maximum turn":"最大旋回角","Beats per line":"1行あたりの拍数","Blade Curl":"ブレードの曲率","Blade Spread":"ブレードの広がり","Blades":"ブレード数","Bottom to Top":"下から上","Cycles":"周期数","End radius":"終了半径","Explicit":"陽関数","Implicit":"陰関数","Parametric":"媒介変数","Inner Circle":"内側円","Inner Circle Radius":"内側円の半径","Inner Radius":"内側半径","Inner radius":"内側半径","Left to Right":"左から右","Length":"長さ","Lines":"行数","Outer Radius":"外側半径","Outer radius":"外側半径","Phase":"位相","Radius Growth":"半径の増加","Radius X":"X半径","Radius Y":"Y半径","Resolution":"解像度","Right to Left":"右から左","Segments":"セグメント数","Side length":"辺の長さ","Star points":"星の頂点数","Start angle":"開始角度","Start radius":"開始半径","Sweep angle":"掃引角度","Top to Bottom":"上から下","Turns":"回転数","Wander Seed":"揺らぎシード","Wander Strength":"揺らぎ強度","X Maximum":"X最大値","X Minimum":"X最小値","Y Maximum":"Y最大値","Y Minimum":"Y最小値","t Maximum":"t最大値","t Minimum":"t最小値","Amplitude":"振幅","Graph Size (%)":"グラフサイズ (%)","Graph Type":"グラフ形式","Text":"テキスト","Text Size (%)":"テキストサイズ (%)","Auto Arrange":"自動配置","Margin X":"X余白","Margin Y":"Y余白","Center X":"中心X","Center Y":"中心Y","Width":"幅","Height":"高さ","Radius":"半径","Start Angle":"開始角度","End Angle":"終了角度","Angle":"角度","Seed":"シード","Steps":"ステップ数","Enabled":"有効","Disabled":"無効","Forward":"順方向","Reverse":"逆方向","Clockwise":"時計回り","Counterclockwise":"反時計回り","Restart Each Chunk":"チャンクごとに先頭から","Back and Forth":"往復","Top to Bottom / Left to Right":"上から下 / 左から右","Top to Bottom / Right to Left":"上から下 / 右から左","Linear":"直線","Ease In":"イーズイン","Ease Out":"イーズアウト",
"Drawing":"描画","Undo":"元に戻す","Redo":"やり直す","Clear":"クリア","Import Image...":"画像をインポート...","Draw at least one stroke before pressing OK.":"OKを押す前に少なくとも1本の線を描いてください。","Draw one or more strokes. Notes are placed top-to-bottom, then horizontally within each row. Ctrl+Z: undo, Ctrl+Y: redo.":"1本以上の線を描いてください。ノーツは上から下へ、各行では横方向に配置されます。Ctrl+Z: 元に戻す、Ctrl+Y: やり直す。",
"Import Image as Drawing":"画像を描画としてインポート","No image selected":"画像が選択されていません","Choose Image...":"画像を選択...","Choose Image":"画像を選択","Images (*.png *.jpg *.jpeg *.webp *.bmp)":"画像 (*.png *.jpg *.jpeg *.webp *.bmp)","Dark Lines":"暗い線","Light Lines":"明るい線","Alpha Outline":"アルファ輪郭","Trace Mode":"トレースモード","Threshold":"しきい値","Minimum Outline Length":"最小輪郭長","Simplification":"単純化","Invert":"反転","Refresh Preview":"プレビューを更新","Import into Drawing":"描画にインポート","Image tracing failed":"画像のトレースに失敗しました","Threshold controls which pixels count as lines. Minimum Outline Length removes tiny noise loops. Simplification reduces point count after tracing; increase it for faster Drawing previews and cleaner outlines.":"しきい値は線として扱うピクセルを決めます。最小輪郭長は小さなノイズ輪郭を除去します。単純化はトレース後の点数を減らします。描画プレビューを高速化し、輪郭を整理するには値を上げてください。",
"Settings":"設定","General":"一般","Language":"言語","Shortcuts":"ショートカット","Advanced":"詳細設定","Restore Defaults":"既定値に戻す","Confirm before overwriting original beatmap":"元の譜面を上書きする前に確認する","Restart Taiko Fancy Arranger to apply the interface language.":"インターフェイスの言語を適用するにはTaiko Fancy Arrangerを再起動してください。","Restart required":"再起動が必要です","Please restart Taiko Fancy Arranger to apply the language change.":"言語の変更を適用するにはTaiko Fancy Arrangerを再起動してください。","Action":"操作","Category":"カテゴリ","Shortcut":"ショートカット","Settings storage location:":"設定の保存場所:","Reset all settings":"すべての設定をリセット","Clear every saved setting and restore defaults?":"保存されたすべての設定を消去して既定値に戻しますか？","Use Reset all settings to clear every saved setting.":"保存済みの設定をすべて消去するには「すべての設定をリセット」を使用してください。",
"Adjust by 0.01":"0.01ずつ調整","All applied transformations reset.":"適用したすべての変形をリセットしました。","Apply failed":"適用に失敗しました","Background copy failed":"背景のコピーに失敗しました","Choose a different filename.":"別のファイル名を選択してください。","Export complete":"エクスポート完了","Export failed":"エクスポートに失敗しました","Open failed":"開けませんでした","Open a map first":"先に譜面を開いてください","Open a beatmap before adding a background.":"背景を追加する前に譜面を開いてください。","Open a map to begin.":"開始するには譜面を開いてください。","Original updated":"元のファイルを更新しました","Overwrite original beatmap?":"元の譜面を上書きしますか？","Select notes in the bottom timeline first.":"先に下部タイムラインでノーツを選択してください。","Show or hide equation keyboard":"方程式キーボードを表示または非表示","Source protected":"元のファイルは保護されています","This writes every committed transformation to the original .osu file. Continue?":"確定したすべての変形を元の.osuファイルに書き込みます。続行しますか？","Write failed":"書き込みに失敗しました","Swap transformation, parameters, and position between Don and Kat":"ドンとカッの変形、パラメータ、位置を入れ替えます","Swapped Don and Kat transformations.":"ドンとカッの変形を入れ替えました。","Open Drawing Window and draw a shape to preview.":"描画ウィンドウを開き、プレビューする形を描いてください。","Preview reset to original coordinates.":"プレビューを元の座標に戻しました。",
}
NOUN={"Drawing":"描画","Pinwheel":"ピンホイール","Line":"直線","Row":"行","Column":"列","Circle":"円","Wave":"波","Zigzag":"ジグザグ","Spiral":"らせん","Arc":"円弧","Star":"星","Triangle":"三角形","Square":"四角形","Diamond":"ひし形","Text":"テキスト","Chunk":"チャンク","Blade":"ブレード","Turn":"回転"}
def translate(source: str) -> str | None:
    if source in JA:return JA[source]
    m=re.fullmatch(r"Notes per (.+)",source)
    if m:return f"{NOUN.get(m.group(1),m.group(1))}あたりのノーツ数"
    m=re.fullmatch(r"(.+) Notes",source)
    if m:return f"{NOUN.get(m.group(1),m.group(1))}のノーツ数"
    return None